#ifndef INCLUDE_CLOCK_CONFIG_C_
#define INCLUDE_CLOCK_CONFIG_C_

#include "clock_config.h"
#include "ClockManager.h"
#include "chip.h"

void BootClock_Init(){

#if BOARD_BOOTCLOCKRUN_SRC_Core_CLK_DEF
    CRM_SysPll_Init(BOARD_BOOTCLOCKRUN_SRC_CORE_CFG_PARA);
#endif
#if BOARD_BOOTCLOCKRUN_SRC_Peri_CLK_DEF
    CRM_SysPll_Init(BOARD_BOOTCLOCKRUN_SRC_PERI_CFG_PARA);
#endif
#if BOARD_BOOTCLOCKRUN_SRC_Flash_CLK_DEF
    CRM_SysPll_Init(BOARD_BOOTCLOCKRUN_SRC_FLASH_CFG_PARA);
#endif
#if BOARD_BOOTCLOCKRUN_SRC_Psram_CLK_DEF
    CRM_SysPll_Init(BOARD_BOOTCLOCKRUN_SRC_PSRAM_CFG_PARA);
#endif
#if BOARD_BOOTCLOCKRUN_SRC_Sdio_CLK_DEF
    CRM_SysPll_Init(BOARD_BOOTCLOCKRUN_SRC_SDIO_CFG_PARA);
#endif

#if BOARD_BOOTCLOCKRUN_SYSCLK_CLK_DEF
    // SYSCLK

    HAL_CRM_SetSysclkClkSrc(BOARD_BOOTCLOCKRUN_SYSCLK_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_HCLK_CLK_DEF
    // HCLK

    HAL_CRM_SetHclkClkDiv(BOARD_BOOTCLOCKRUN_HCLK_CLK_N, BOARD_BOOTCLOCKRUN_HCLK_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_CMN_PCLK_CLK_DEF
    // CMN_PCLK

    HAL_CRM_SetCmn_pclkClkDiv(BOARD_BOOTCLOCKRUN_CMN_PCLK_CLK_N, BOARD_BOOTCLOCKRUN_CMN_PCLK_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_AON_CFG_PCLK_CLK_DEF
    // AON_CFG_PCLK

    HAL_CRM_SetAon_cfg_pclkClkDiv(BOARD_BOOTCLOCKRUN_AON_CFG_PCLK_CLK_N, BOARD_BOOTCLOCKRUN_AON_CFG_PCLK_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_PSRAM_CLK_DEF
    // PSRAM

    HAL_CRM_SetPsramClkDiv(BOARD_BOOTCLOCKRUN_PSRAM_CLK_M);

    HAL_CRM_SetPsramClkSrc(BOARD_BOOTCLOCKRUN_PSRAM_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_MTIME_CLK_DEF
    // MTIME

    HAL_CRM_SetMtimeClkDiv(BOARD_BOOTCLOCKRUN_MTIME_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_FLASH_CLK_DEF
    // FLASH

    HAL_CRM_SetFlashClkDiv(BOARD_BOOTCLOCKRUN_FLASH_CLK_M);

    HAL_CRM_SetFlashClkSrc(BOARD_BOOTCLOCKRUN_FLASH_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_SPI0_CLK_DEF
    // SPI0

    HAL_CRM_SetSpi0ClkDiv(BOARD_BOOTCLOCKRUN_SPI0_CLK_N, BOARD_BOOTCLOCKRUN_SPI0_CLK_M);

    HAL_CRM_SetSpi0ClkSrc(BOARD_BOOTCLOCKRUN_SPI0_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_UART0_CLK_DEF
    // UART0

    HAL_CRM_SetUart0ClkDiv(BOARD_BOOTCLOCKRUN_UART0_CLK_N, BOARD_BOOTCLOCKRUN_UART0_CLK_M);

    HAL_CRM_SetUart0ClkSrc(BOARD_BOOTCLOCKRUN_UART0_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_SPI1_CLK_DEF
    // SPI1

    HAL_CRM_SetSpi1ClkDiv(BOARD_BOOTCLOCKRUN_SPI1_CLK_N, BOARD_BOOTCLOCKRUN_SPI1_CLK_M);

    HAL_CRM_SetSpi1ClkSrc(BOARD_BOOTCLOCKRUN_SPI1_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_UART1_CLK_DEF
    // UART1

    HAL_CRM_SetUart1ClkDiv(BOARD_BOOTCLOCKRUN_UART1_CLK_N, BOARD_BOOTCLOCKRUN_UART1_CLK_M);

    HAL_CRM_SetUart1ClkSrc(BOARD_BOOTCLOCKRUN_UART1_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_SDIOH_CLK_DEF
    // SDIOH

    HAL_CRM_SetSdiohClkDiv(BOARD_BOOTCLOCKRUN_SDIOH_CLK_N, BOARD_BOOTCLOCKRUN_SDIOH_CLK_M);

    HAL_CRM_SetSdiohClkSrc(BOARD_BOOTCLOCKRUN_SDIOH_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_UART2_CLK_DEF
    // UART2

    HAL_CRM_SetUart2ClkDiv(BOARD_BOOTCLOCKRUN_UART2_CLK_N, BOARD_BOOTCLOCKRUN_UART2_CLK_M);

    HAL_CRM_SetUart2ClkSrc(BOARD_BOOTCLOCKRUN_UART2_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_VIC_OUT_CLK_DEF
    // VIC_OUT

    HAL_CRM_SetVic_outClkDiv(BOARD_BOOTCLOCKRUN_VIC_OUT_CLK_M);

    HAL_CRM_SetVic_outClkSrc(BOARD_BOOTCLOCKRUN_VIC_OUT_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_GPT_CLK_DEF
    // GPT

    HAL_CRM_SetGptClkDiv(BOARD_BOOTCLOCKRUN_GPT_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_I8080_CLK_DEF
    // I8080

    HAL_CRM_SetI8080ClkDiv(BOARD_BOOTCLOCKRUN_I8080_CLK_M);

    HAL_CRM_SetI8080ClkSrc(BOARD_BOOTCLOCKRUN_I8080_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_IR_CLK_DEF
    // IR

    HAL_CRM_SetIrClkDiv(BOARD_BOOTCLOCKRUN_IR_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_GPADC_CLK_DEF
    // GPADC

    HAL_CRM_SetGpadcClkDiv(BOARD_BOOTCLOCKRUN_GPADC_CLK_M);

#endif

#if BOARD_BOOTCLOCKRUN_I2S0_CLK_DEF
    // I2S0

    HAL_CRM_SetI2s0ClkSrc(BOARD_BOOTCLOCKRUN_I2S0_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_I2S1_CLK_DEF
    // I2S1

    HAL_CRM_SetI2s1ClkSrc(BOARD_BOOTCLOCKRUN_I2S1_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_RGB_CLK_DEF
    // RGB

    HAL_CRM_SetRgbClkDiv(BOARD_BOOTCLOCKRUN_RGB_CLK_M);

    HAL_CRM_SetRgbClkSrc(BOARD_BOOTCLOCKRUN_RGB_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_VIC_CLK_DEF
    // VIC

    HAL_CRM_SetVicClkSrc(BOARD_BOOTCLOCKRUN_VIC_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_QSPI1_CLK_DEF
    // QSPI1

    HAL_CRM_SetQspi1ClkDiv(BOARD_BOOTCLOCKRUN_QSPI1_CLK_N, BOARD_BOOTCLOCKRUN_QSPI1_CLK_M);

    HAL_CRM_SetQspi1ClkSrc(BOARD_BOOTCLOCKRUN_QSPI1_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_QSPI0_CLK_DEF
    // QSPI0

    HAL_CRM_SetQspi0ClkDiv(BOARD_BOOTCLOCKRUN_QSPI0_CLK_N, BOARD_BOOTCLOCKRUN_QSPI0_CLK_M);

    HAL_CRM_SetQspi0ClkSrc(BOARD_BOOTCLOCKRUN_QSPI0_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_DAC_CLK_DEF
    // DAC

    HAL_CRM_SetDacClkSrc(BOARD_BOOTCLOCKRUN_DAC_CLK_SRC);

#endif

#if BOARD_BOOTCLOCKRUN_ADC_CLK_DEF
    // ADC

    HAL_CRM_SetAdcClkSrc(BOARD_BOOTCLOCKRUN_ADC_CLK_SRC);

#endif

}
#endif /* INCLUDE_CLOCK_CONFIG_C_ */