TOPDIR=../../../..

exclude_dirs =

# Define subdirectories to build
SUBDIRS = spi_master_pol0_pha0 \
          spi_master_pol0_pha1 \
          spi_master_pol1_pha0 \
          spi_master_pol1_pha1
 
include $(TOPDIR)/rules.mk

